labelinator <- function(x, labels = metric_labels){
  match_order <- match(x, labels)
  labels_sel <- names(labels)[match_order]
  return(labels_sel)
}

inv_labelinator <- function(x, labels = metric_labels){
  match_order <- match(x, names(labels))
  vars_sel <- unname(labels[match_order])
  return(vars_sel)
}

metric_labels <- c(
  'Mean Annual Q' = 'Q_mean',
  'Mean Jan Q' = 'Q_mean_monthly_1',
  'Mean Feb Q' = 'Q_mean_monthly_2',
  'Mean Mar Q' = 'Q_mean_monthly_3',
  'Mean Apr Q' = 'Q_mean_monthly_4',
  'Mean May Q' = 'Q_mean_monthly_5',
  'Mean Jun Q' = 'Q_mean_monthly_6',
  'Mean Jul Q' = 'Q_mean_monthly_7',
  'Mean Aug Q' = 'Q_mean_monthly_8',
  'Mean Sep Q' = 'Q_mean_monthly_9',
  'Mean Oct Q' = 'Q_mean_monthly_10',
  'Mean Nov Q' = 'Q_mean_monthly_11',
  'Mean Dec Q' = 'Q_mean_monthly_12',
  'Q5' = 'Q5',
  'Q10' = 'Q10',
  'Q90' = 'Q90',
  'Q95' = 'Q95',
  'Q95 - Q10' = 'Q95_minus_Q10',
  'Runoff Ratio' = 'TotalRR',
  '# High Flow Events (>3x)' = 'Q_frequency_high_1',
  '# High Flow Events (>6x)' = 'Q_frequency_high_2',
  '# High Flow Events (>9x)' = 'Q_frequency_high_3',
  '# High Flow Events (>12x)' = 'Q_frequency_high_4',
  '# High Flow Events (>15x)' = 'Q_frequency_high_5',
  '# Low Flow Events (<0.75x)' = 'Q_frequency_low_1',
  '# Low Flow Events (<0.67x)' = 'Q_frequency_low_2',
  '# Low Flow Events (<0.5x)' = 'Q_frequency_low_3',
  '# Low Flow Events (<0.33x)' = 'Q_frequency_low_4',
  '# Low Flow Events (<0.25x)' = 'Q_frequency_low_5',
  '# No Flow Events' = 'Q_frequency_noflow',
  'Duration High Flow (>3x)' = 'Q_totalduration_high_1',
  'Duration High Flow (>6x)' = 'Q_totalduration_high_2',
  'Duration High Flow (>9x)' = 'Q_totalduration_high_3',
  'Duration High Flow (>12x)' = 'Q_totalduration_high_4',
  'Duration High Flow (>15x)' = 'Q_totalduration_high_5',
  'Duration Low Flow (<0.75x)' = 'Q_totalduration_low_1',
  'Duration Low Flow (<0.67x)' = 'Q_totalduration_low_2',
  'Duration Low Flow (<0.5x)' = 'Q_totalduration_low_3',
  'Duration Low Flow (<0.33x)' = 'Q_totalduration_low_4',
  'Duration Low Flow (<0.25x)' = 'Q_totalduration_low_5',
  'Duration No Flow' = 'Q_totalduration_noflow',
  'Mean Duration High Flow Events (>3x)' = 'Q_meanduration_high_1',
  'Mean Duration High Flow Events (>6x)' = 'Q_meanduration_high_2',
  'Mean Duration High Flow Events (>9x)' = 'Q_meanduration_high_3',
  'Mean Duration High Flow Events (>12x)' = 'Q_meanduration_high_4',
  'Mean Duration High Flow Events (>15x)' = 'Q_meanduration_high_5',
  'Mean Duration Low Flow Events (<0.75x)' = 'Q_meanduration_low_1',
  'Mean Duration Low Flow Events (<0.67x)' = 'Q_meanduration_low_2',
  'Mean Duration Low Flow Events (<0.5x)' = 'Q_meanduration_low_3',
  'Mean Duration Low Flow Events (<0.33x)' = 'Q_meanduration_low_4',
  'Mean Duration Low Flow Events (<0.25x)' = 'Q_meanduration_low_5',
  'Mean Duration No Flow Events' = 'Q_meanduration_noflow',
  'Half Flow Date' = 'HFD_mean',
  'Half Flow Interval' = 'HFI_mean',
  'Max Q Date' = 'peakQ_timing',
  'Baseflow Index' = 'BFI',
  'Flashiness Index' = 'FlashinessIndex',
  'Rising Limb Density' = 'RLD',
  'FDC Midsection Slope' = 'FDC_slope',
  'Recession Constant' = 'BaseflowRecessionK',
  'Recession Seasonality' = 'Recession_a_Seasonality'
)

pred_labels <- c(
  'Precip (annual)' = 'precip_annual',
  'Temp (annual)' = 'temp_annual',
  'PET (annual)' = 'pet_annual',
  'P/PET (annual)' = 'ppet_annual',
  'Previous Precip' = 'precip_annual_prev',
  'Previous Temp' = 'temp_annual_prev',
  'Previous PET' = 'pet_annual_prev',
  'Precip (winter)' = 'precip_jfm',
  'Temp (winter)' = 'temp_jfm',
  'PET (winter)' = 'pet_jfm',
  'P/PET (winter)' = 'ppet_jfm',
  'Precip (spring)' = 'precip_amj',
  'Temp (spring)' = 'temp_amj',
  'PET (spring)' = 'pet_amj',
  'P/PET (spring)' = 'ppet_amj',
  'Precip (summer)' = 'precip_jas',
  'Temp (summer)' = 'temp_jas',
  'PET (summer)' = 'pet_jas',
  'P/PET (summer)' = 'ppet_jas',
  'Precip (fall)' = 'precip_ond',
  'Temp (fall)' = 'temp_ond',
  'PET (fall)' = 'pet_ond',
  'P/PET (fall)' = 'ppet_ond',
  'Precip Seasonality' = 'si',
  'SWE Max' = 'max_swe',
  'SWE Max Day' = 'max_swe_day',
  'SWE Annual Total' = 'swe_annual',
  'SWE Persistence' = 'swe_persistence',
  'SWE Zero Day' = 'zero_swe_day',
  'Snowmelt Duration' = 'melt_duration',
  '% Agriculture' = 'ag',
  '% Developed' = 'developed',
  '% Forest' = 'forest',
  '% Grassland' = 'grass',
  '% Water' = 'water',
  '% Barren' = 'barren',
  '% Tile Drainage' = 'tile_pct',
  'Water Use' = 'water_use',
  'Drainage Area' = 'drainage_area',
  'Mean Elevation' = 'elev',
  'Mean Slope' = 'slope',
  'TWI' = 'twi',
  'Soil Permeability' = 'soil_perm',
  'Soil AWC' = 'soil_awc',
  'Disturbance Index' = 'dist_index',
  'Geologic Age' = 'age',
  'Mean Precip' = 'precip_mean',
  'Mean Temp' = 'temp_mean',
  'Mean PET' = 'pet_mean',
  'Mean Precip Seasonality' = 'si_mean',
  'Mean Q' = 'q_norm_mean',
  'Mean Water Use' = 'water_use_mean'
)

pred_cats <- c(
  'Precip' = 'precip_annual',
  'Temp' = 'temp_annual',
  'PET' = 'pet_annual',
  'P/PET' = 'ppet_annual',
  'Precip' = 'precip_annual_prev',
  'Temp' = 'temp_annual_prev',
  'PET' = 'pet_annual_prev',
  'Precip' = 'precip_jfm',
  'Temp' = 'temp_jfm',
  'PET' = 'pet_jfm',
  'P/PET' = 'ppet_jfm',
  'Precip' = 'precip_amj',
  'Temp' = 'temp_amj',
  'PET' = 'pet_amj',
  'P/PET' = 'ppet_amj',
  'Precip' = 'precip_jas',
  'Temp' = 'temp_jas',
  'PET' = 'pet_jas',
  'P/PET' = 'ppet_jas',
  'Precip' = 'precip_ond',
  'Temp' = 'temp_ond',
  'PET' = 'pet_ond',
  'P/PET' = 'ppet_ond',
  'Precip' = 'si',
  'Snow' = 'max_swe',
  'Snow' = 'max_swe_day',
  'Snow' = 'swe_annual',
  'Snow' = 'swe_persistence',
  'Snow' = 'zero_swe_day',
  'Snow' = 'melt_duration',
  'Land Cover' = 'ag',
  'Land Cover' = 'developed',
  'Land Cover' = 'forest',
  'Land Cover' = 'grass',
  'Land Cover' = 'water',
  'Land Cover' = 'barren',
  'Hydro Mod.' = 'tile_pct',
  'Hydro Mod.' = 'water_use',
  'Topography' = 'drainage_area',
  'Topography' = 'elev',
  'Topography' = 'slope',
  'Topography' = 'twi',
  'Geology/Soil' = 'soil_perm',
  'Geology/Soil' = 'soil_awc',
  'Hydro Mod.' = 'dist_index',
  'Geology/Soil' = 'age',
  'Precip' = 'precip_mean',
  'Temp' = 'temp_mean',
  'PET' = 'pet_mean',
  'Precip' = 'si_mean',
  'Mean Q' = 'q_norm_mean',
  'Hydro Mod.' = 'water_use_mean'
)

pred_cat_colors <- c(
  'Precip' = '#f8766d',
  'PET' = '#c49a00',
  'Snow' = '#53b400',
  'Land Cover' = '#00c094',
  'Hydro Mod.' = '#00b6eb',
  'Topography' = '#a58aff',
  'Geology/Soil' = '#fb61d7'
)
